Add NonEmptyPinboard
bossmc/pinboard pull request #1
Opened 2017-06-08 13:26 UTC by chriscoomber

This new variant of `Pinboard` can never be empty.

This is useful if the user doesn't want to have to deal with handling `Option`s as a result of `Pinboard::read`, and they don't mind the lack of `Pinboard::clear`.

The implementation uses `unwrap`s, as we can't convince the compiler that the underlying `Atomic` pointer is never null.

2017-06-08 16:08 UTC, bossmc requested changes
Ok, I'm pretty happy to add this, some comments inline.

2017-06-08 16:08 UTC, bossmc commented on src/lib.rs
> +        self.0.read().unwrap()
Can this be an `expect` with a good error string?

2017-06-08 16:08 UTC, bossmc commented on src/lib.rs
> +    pub fn set(&self, t: T) {
`#[inline(always)]`?

2017-06-08 16:08 UTC, bossmc commented on src/lib.rs
> +    pub fn set(&self, t: T) {
And below.

2017-06-09 13:04 UTC, chriscoomber commented on src/lib.rs
> +    pub fn set(&self, t: T) {
I don't know  the rules for `inline` - [this answer](https://stackoverflow.com/a/37639889/5437033) seems to indicate that it isn't worth it for small functions?

2017-06-09 14:14 UTC, bossmc commented on src/lib.rs
> +    pub fn set(&self, t: T) {
It's worth marking it at at least `#[inline]` so the bytecode is made available for linked crates (rather than just inlining in this crate).

2017-06-09 14:16 UTC, bossmc commented on src/lib.rs
> +                              https://github.com/bossmc/pinboard/issues.")
Can this be an `unreachable!()`?

2017-06-09 16:18 UTC, bossmc approved these changes

2017-06-09 16:18 UTC, merged